/**
 * app/api/ai/chat/route.ts — OpenRouter version
 *
 * INTERVIEW POINT — Why OpenRouter over direct Gemini:
 * OpenRouter is a unified LLM gateway. One API key, one request format,
 * 200+ models. Swap the model string in .env with zero code changes.
 * It uses the OpenAI-compatible Chat Completions format — the industry standard.
 * If Gemini quota runs out, switch to "anthropic/claude-3-5-haiku" instantly.
 *
 * INTERVIEW POINT — OpenAI-compatible format:
 * This is the de facto standard for LLM APIs. OpenRouter, Azure OpenAI,
 * Groq, Together, Anyscale all speak it. Learning it once works everywhere:
 *   POST /v1/chat/completions
 *   { model, messages: [{role, content}], stream, temperature, max_tokens }
 *
 * INTERVIEW POINT — temperature parameter:
 * 0.0 = deterministic (same input → same output)
 * 1.0 = highly creative/random
 * 0.3 = factual with slight variation — correct for tax advice
 */

import { NextRequest, NextResponse } from "next/server"

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY
const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL ?? "google/gemini-2.0-flash-001"
const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

function buildSystemPrompt(summary: Record<string, unknown>): string {
  const netPnl =
    Number(summary.netFnoPnl ?? 0) +
    Number(summary.netIntradayPnl ?? 0) +
    Number(summary.netDeliveryPnl ?? 0)

  return `You are a knowledgeable Indian tax expert specializing in F&O and equity trading taxation. You are helping a trader understand their tax assessment generated by TraderOS.

## User's Actual Tax Assessment Data
Base ALL your answers strictly on these numbers. Do not invent figures.

**Turnover (ICAI 8th Edition)**
- F&O Turnover: ₹${summary.fnoTurnover}
- Intraday Equity Turnover: ₹${summary.intradayTurnover}
- Delivery Equity Turnover: ₹${summary.deliveryTurnover}

**Profit & Loss**
- F&O Net P&L: ₹${summary.netFnoPnl}
- Intraday Net P&L: ₹${summary.netIntradayPnl}
- Delivery Net P&L: ₹${summary.netDeliveryPnl}
- Combined Net P&L: ₹${netPnl.toFixed(2)}

**Tax Assessment**
- ITR Form: ${summary.itrForm}
- Tax Audit Required: ${summary.auditRequired ? "YES" : "NO"}
- Audit Reason: ${summary.auditReason}
- Tax Regime: ${summary.taxRegime ?? "New"}

**Advance Tax (Section 211)**
- Q1 due 15 Jun: ₹${summary.advanceTaxQ1}
- Q2 due 15 Sep: ₹${summary.advanceTaxQ2}
- Q3 due 15 Dec: ₹${summary.advanceTaxQ3}
- Q4 due 15 Mar: ₹${summary.advanceTaxQ4}

**Deductions (Section 37)**
- Estimated deductible expenses: ₹${summary.deductibleExpenses}

## Rules
- Only answer about THIS user's situation using the data above
- Cite relevant sections (44AB, 70, 71, 234B, 234C, 37)
- Use ₹ symbol. Be concise — user is not a tax expert
- Never invent numbers not present above
- Recommend a CA for actual filing but explain the process
- Respond in the same language the user writes in`
}

export async function POST(request: NextRequest) {
  if (!OPENROUTER_API_KEY) {
    return NextResponse.json(
      { error: "AI not configured. Add OPENROUTER_API_KEY to .env.local" },
      { status: 503 }
    )
  }

  const body = await request.json()
  const { messages, summary } = body as {
    messages: Array<{ role: string; content: string }>
    summary: Record<string, unknown>
  }

  if (!messages?.length || !summary) {
    return NextResponse.json({ error: "Missing messages or summary" }, { status: 400 })
  }

  const openAiMessages = [
    { role: "system", content: buildSystemPrompt(summary) },
    ...messages.map((m) => ({
      role: m.role === "assistant" ? "assistant" : "user",
      content: m.content,
    })),
  ]

  try {
    const aiResponse = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
        "HTTP-Referer": process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
        "X-Title": "TraderOS",
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        messages: openAiMessages,
        stream: true,
        temperature: 0.3,
        max_tokens: 1024,
      }),
    })

    if (!aiResponse.ok) {
      const err = await aiResponse.text()
      console.error("OpenRouter error:", aiResponse.status, err)
      return NextResponse.json({ error: `AI error: ${aiResponse.status}` }, { status: 502 })
    }

    if (!aiResponse.body) {
      return NextResponse.json({ error: "No stream" }, { status: 502 })
    }

    // Transform OpenRouter SSE → our simplified SSE format
    // OpenRouter: data: {"choices":[{"delta":{"content":"Hi"}}]}
    // Ours:       data: {"text":"Hi"}
    const { readable, writable } = new TransformStream()
    const writer = writable.getWriter()
    const encoder = new TextEncoder()
    const decoder = new TextDecoder()

    ;(async () => {
      const reader = aiResponse.body!.getReader()
      try {
        while (true) {
          const { done, value } = await reader.read()
          if (done) break

          for (const line of decoder.decode(value, { stream: true }).split("\n")) {
            if (!line.startsWith("data: ")) continue
            const data = line.slice(6).trim()
            if (!data || data === "[DONE]") continue
            try {
              const text = JSON.parse(data).choices?.[0]?.delta?.content ?? ""
              if (text) {
                await writer.write(encoder.encode(`data: ${JSON.stringify({ text })}\n\n`))
              }
            } catch { /* skip malformed */ }
          }
        }
        await writer.write(encoder.encode("data: [DONE]\n\n"))
      } catch (e) {
        console.error("Stream error:", e)
      } finally {
        await writer.close()
      }
    })()

    return new Response(readable, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache, no-transform",
        Connection: "keep-alive",
      },
    })
  } catch (err) {
    console.error("AI route error:", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}